---
argument_specs:
  main:
    short_description: Restore network configuration from backup.
    description:
      - This role restores a network configuration from a previously taken backup, using either a local or SCM data store.
    author:
      - Rohit Thakur (rohitthakur2590)
    options:
      data_store:
        description:
          - Specifies the data store configuration from which the backup will be restored. This can include either a local path or an SCM configuration or SSH.
        type: dict
        required: true
        options:
          local:
            description:
              - Specifies the local data store.
            type: dict
            required: false
            options:
              path:
                type: str
                required: true
                description:
                  - Path inside the SCM repository where the backup will be saved (e.g., data/backups/<date>/<platform>).
              filename:
                type: str
                required: true
                description:
                  - Filename for the backup stored in the SCM (e.g., <platform>_<date>.txt).
          scm:
            description:
              - Specifies the SCM data store.
            type: dict
            required: false
            options:
              origin:
                type: dict
                required: true
                options:
                  url:
                    type: str
                    required: true
                    description:
                      - URL of the SCM repository (e.g., GitHub) where the backup file is stored.
                  token:
                    type: str
                    required: true
                    no_log: true
                    description:
                      - Authentication token for accessing the SCM repository.
                  path:
                    type: str
                    required: true
                    description:
                      - Path inside the SCM repository where the backup will be saved (e.g., data/backups/<date>/<platform>).
                  filename:
                    type: str
                    required: true
                    description:
                      - Filename for the backup stored in the SCM (e.g., <platform>_<date>.txt).
          ssh:
            description:
              - Specifies the SSH-based data store to retrieve backups from.
            type: dict
            required: false
            options:
              host:
                type: str
                required: true
                description:
                  - Hostname or IP address of the SSH server.
              port:
                type: int
                required: false
                description:
                  - SSH port.
              user:
                type: str
                required: true
                description:
                  - SSH username for authentication.
              path:
                type: str
                required: true
                description:
                  - Remote path on the SSH server where the backup file is located.
              filename:
                type: str
                required: true
                description:
                  - Filename of the backup to restore.
              keyfile:
                type: str
                required: false
                description:
                  - Path to private key file for SSH authentication.
              inline_key:
                type: str
                required: false
                no_log: true
                description:
                  - Inline private key string.
